apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-controller
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-controller-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: amazon-network-policy-controller-k8s
    app.kubernetes.io/part-of: amazon-network-policy-controller-k8s
    app.kubernetes.io/managed-by: kustomize
  name: controller-controller-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-controller
